### ISSUE TITLE
Demo link is dead.

### ISSUE THREAD

**Issue by sparky672** [tazsingh/will_pickdate#11]
The link to the demo page is giving a 404.

http://zenapsis.github.com/will_pickdate/

I hope this is simply an oversight and not an indication of this product's health.

Thank-you!

**Comment by tazsingh** [comment]
Hey @sparky672, that's because the demo/project has moved to: http://tazsingh.github.com/will_pickdate/

Where did you come across that link? If it's on a blog, you may want to contact the author and inform them of the change.

Thanks!

**Comment by sparky672** [comment]
_"Where did you come across that link?"_

From [this Github page](https://github.com/tazsingh/will_pickdate) which is coming from the [README](https://github.com/tazsingh/will_pickdate/blob/master/README.markdown)....  where it says, _"Check it out Here"_

![will_pickdate](https://f.cloud.github.com/assets/586756/305857/0b763cca-9666-11e2-88f2-cc4cda34a05a.jpg)
