### ISSUE TITLE
datetime picker does not load value on initialization

### ISSUE THREAD

**Issue by g8d3** [tazsingh/will_pickdate#7]
I'm using this:

``` javascript
$('input').will_pickdate({
  timePicker: true,
  format: 'j F Y @ h:iA',
  inputOutputFormat: 'Y-m-d H:i:s'
});
```

On initialization, the input element shows, for example, `12 June 2012 10:45`, but `$('input').val()` returns `''` when it should return the displayed datetime.

Then, when I select a datetime `$('input').val()` returns selected datetime correctly

**Comment by tazsingh** [comment]
Thanks. I have confirmed this bug and will fix it soon.
