### ISSUE TITLE
how to override default options object

### ISSUE THREAD

**Issue by g8d3** [tazsingh/will_pickdate#8]
I want to override defaults along all my application, something like `$.extend($.fn.will_pickdate.options, myDefaultsObject)`, and then to use `$('input').will_pickdate()`

How can I do that?

**Comment by tazsingh** [comment]
This feature is already in v0.3.0 and will be available once v0.3.0 is complete.

https://github.com/zenapsis/will_pickdate/blob/v0.3.0/spec/options_spec.js#L38-L46
